### ISSUE TITLE
Unable to analyze candle (OHLCV) data for pair 

### ISSUE THREAD

**Issue by nicolasn95** [iterativv/NostalgiaForInfinity#125]
First problem is 

2021-09-20 03:33:09,763 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair ATOM/USDT: 'safe_pump'
2021-09-20 03:33:10,175 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error 'safe_pump' calling <bound method IStrategy._analyze_ticker_internal of <NostalgiaForInfinityNext.NostalgiaForInfinityNext object at 0x7fcd2273b9a0>>
Traceback (most recent call last):
  File "/mnt/c/Users/85048/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/mnt/c/Users/85048/freqtrade/freqtrade/strategy/interface.py", line 381, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
  File "/mnt/c/Users/85048/freqtrade/freqtrade/strategy/interface.py", line 361, in analyze_ticker
    dataframe = self.advise_buy(dataframe, metadata)
  File "/mnt/c/Users/85048/freqtrade/freqtrade/strategy/interface.py", line 704, in advise_buy
    return self.populate_buy_trend(dataframe, metadata)
  File "/mnt/c/Users/85048/freqtrade/user_data/strategies/NostalgiaForInfinityNext.py", line 4594, in populate_buy_trend
    if global_buy_protection_params["safe_pump"]:
KeyError: 'safe_pump'

And then:

2021-09-20 03:41:18,833 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair SXP/USDT

**Comment by bjwie** [comment]
you tried to update freqtrade itself?

**Comment by bjwie** [comment]
check buy_protection_params it should look like this:

`    buy_protection_params = {
        1: {
            "ema_fast"                  : False,
            "ema_fast_len"              : "26",
            "ema_slow"                  : True,
            "ema_slow_len"              : "12",
            "close_above_ema_fast"      : False,
            "close_above_ema_fast_len"  : "200",
            "close_above_ema_slow"      : False,
            "close_above_ema_slow_len"  : "200",
            "sma200_rising"             : False,
            "sma200_rising_val"         : "28",
            "sma200_1h_rising"          : False,
            "sma200_1h_rising_val"      : "50",
            "safe_dips_threshold_0"     : 0.028,
            "safe_dips_threshold_2"     : 0.3,
            "safe_dips_threshold_12"    : 0.48,
            "safe_dips_threshold_144"   : 0.9,
            "safe_pump"                 : False,
            "safe_pump_type"            : "70",
            "safe_pump_period"          : "24",
            "btc_1h_not_downtrend"      : False,
            "close_over_pivot_type"     : "none", # pivot, sup1, sup2, sup3, res1, res2, res3
            "close_over_pivot_offset"   : 1.0,
            "close_under_pivot_type"    : "none", # pivot, sup1, sup2, sup3, res1, res2, res3
            "close_under_pivot_offset"  : 1.0
        },`

**Comment by eSeR1805** [comment]
Probably some intermediate version issue or due to local changes. @nicolasn95 is this still an issue?
