### ISSUE TITLE
Exception: inputs are all NaN

### ISSUE THREAD

**Issue by mehmetaliuluc** [iterativv/NostalgiaForInfinity#174]
i had a error when i run the  NostalgiaForInfinityX.py ,  NostalgiaForInfinityNextGen.py NostalgiaForInfinityNext.py  . could you please help me for solution

2021-12-18 00:34:23,725 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2021-12-18 00:34:23,725 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_types' with value in config file: {'buy': 'limit', 'sell': 'limit', 'emergencysell': 'limit', 'forcebuy': 'limit', 'forcesell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}.
2021-12-18 00:34:23,725 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2021-12-18 00:34:23,725 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 20.
2021-12-18 00:34:23,725 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 15, 'sell': 35, 'unit': 'minutes', 'exit_timeout_count': 0}.
2021-12-18 00:34:23,725 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 100.0}
2021-12-18 00:34:23,725 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2021-12-18 00:34:23,725 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.99
2021-12-18 00:34:23,725 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2021-12-18 00:34:23,725 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.01
2021-12-18 00:34:23,725 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.03
2021-12-18 00:34:23,725 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: True
2021-12-18 00:34:23,725 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2021-12-18 00:34:23,725 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2021-12-18 00:34:23,725 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'emergencysell': 'limit', 'forcebuy': 'limit', 'forcesell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2021-12-18 00:34:23,725 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2021-12-18 00:34:23,725 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2021-12-18 00:34:23,725 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 20
2021-12-18 00:34:23,725 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2021-12-18 00:34:23,726 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 480
2021-12-18 00:34:23,726 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 15, 'sell': 35, 'unit': 'minutes', 'exit_timeout_count': 0}
2021-12-18 00:34:23,726 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2021-12-18 00:34:23,726 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2021-12-18 00:34:23,726 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: True
2021-12-18 00:34:23,726 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_offset: 0.0
2021-12-18 00:34:23,726 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2021-12-18 00:34:23,726 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2021-12-18 00:34:23,726 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-12-18 00:34:23,732 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/home/ubuntu/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
2021-12-18 00:34:23,965 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 480 ...
2021-12-18 00:34:27,552 - freqtrade.optimize.backtesting - INFO - Loading data from 2021-11-17 21:20:00 up to 2021-12-17 21:10:00 (29 days).
2021-12-18 00:34:27,552 - freqtrade.configuration.timerange - WARNING - Moving start-date by 480 candles to account for startup time.
2021-12-18 00:34:27,552 - freqtrade.optimize.backtesting - INFO - Dataload complete. Calculating indicators
2021-12-18 00:34:27,553 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy NostalgiaForInfinityX
2021-12-18 00:34:27,554 - freqtrade.data.history.idatahandler - WARNING - No history data for pair: "BTC/USDT", timeframe: 1h. Use `freqtrade download-data` to download the data
2021-12-18 00:34:27,555 - freqtrade.data.dataprovider - WARNING - No data found for (BTC/USDT, 1h).
2021-12-18 00:34:27,555 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/ubuntu/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/ubuntu/freqtrade/freqtrade/commands/optimize_commands.py", line 54, in start_backtesting
    backtesting.start()
  File "/home/ubuntu/freqtrade/freqtrade/optimize/backtesting.py", line 672, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/home/ubuntu/freqtrade/freqtrade/optimize/backtesting.py", line 627, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "/home/ubuntu/freqtrade/freqtrade/strategy/interface.py", line 833, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/home/ubuntu/freqtrade/freqtrade/strategy/interface.py", line 833, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/home/ubuntu/freqtrade/freqtrade/strategy/interface.py", line 856, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/ubuntu/freqtrade/user_data/strategies/NostalgiaForInfinityX.py", line 8280, in populate_indicators
    btc_info_tf = self.info_tf_btc_indicators(btc_info_tf, metadata)
  File "/home/ubuntu/freqtrade/user_data/strategies/NostalgiaForInfinityX.py", line 8231, in info_tf_btc_indicators
    dataframe['rsi_14'] = ta.RSI(dataframe, timeperiod=14)
  File "talib/_abstract.pxi", line 399, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 441, in talib._ta_lib.Function.__call_function
  File "/home/ubuntu/freqtrade/.env/lib/python3.8/site-packages/talib/__init__.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "talib/_func.pxi", line 4377, in talib._ta_lib.RSI
  File "talib/_func.pxi", line 68, in talib._ta_lib.check_begidx1
Exception: inputs are all NaN

**Comment by eSeR1805** [comment]
Download necessary data. `info_tf_btc` is your hint

**Comment by smajka987** [comment]
I'm experiencing the same issue. I tried `freqtrade download-data` and still inputs are all NaN. 

any input? 

`2022-01-22 22:56:23,027 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 480 ...
2022-01-22 22:56:23,145 - freqtrade.data.history.idatahandler - WARNING - No history data for pair: "XRP/USDT", timeframe: 5m. Use `freqtrade download-data` to download the data
2022-01-22 22:56:23,146 - freqtrade.data.history.idatahandler - WARNING - No history data for pair: "BTC/USDT", timeframe: 1h. Use `freqtrade download-data` to download the data
2022-01-22 22:56:23,146 - freqtrade.data.dataprovider - WARNING - No data found for (BTC/USDT, 1h).
2022-01-22 22:56:23,147 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/steven/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/steven/freqtrade/freqtrade/commands/optimize_commands.py", line 130, in start_edge
    edge_cli.start()
  File "/home/steven/freqtrade/freqtrade/optimize/edge_cli.py", line 49, in start
    result = self.edge.calculate(self.config['exchange']['pair_whitelist'])
  File "/home/steven/freqtrade/freqtrade/edge/edge_positioning.py", line 154, in calculate
    preprocessed = self.strategy.advise_all_indicators(data)
  File "/home/steven/freqtrade/freqtrade/strategy/interface.py", line 839, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/home/steven/freqtrade/freqtrade/strategy/interface.py", line 839, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/home/steven/freqtrade/freqtrade/strategy/interface.py", line 862, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/steven/freqtrade/user_data/strategies/NostalgiaForInfinityX.py", line 9005, in populate_indicators
    btc_info_tf = self.info_tf_btc_indicators(btc_info_tf, metadata)
  File "/home/steven/freqtrade/user_data/strategies/NostalgiaForInfinityX.py", line 8956, in info_tf_btc_indicators
    dataframe['rsi_14'] = ta.RSI(dataframe, timeperiod=14)
  File "talib/_abstract.pxi", line 427, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 472, in talib._ta_lib.Function.__call_function
  File "/home/steven/freqtrade/.env/lib/python3.8/site-packages/talib/__init__.py", line 64, in wrapper
    result = func(*_args, **_kwds)
  File "talib/_func.pxi", line 4377, in talib._ta_lib.RSI
  File "talib/_func.pxi", line 68, in talib._ta_lib.check_begidx1
Exception: inputs are all NaN`
