### ISSUE TITLE
Error loading NFIX strategy. First Timer

### ISSUE THREAD

**Issue by smajka987** [iterativv/NostalgiaForInfinity#188]
This is my first time using a new strategy and changing around the config.json file. Here's the terminal readout

```
2022-01-21 22:36:33,094 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-01-21 22:36:33,094 - freqtrade.freqtradebot - INFO - Starting freqtrade 2021.12
2022-01-21 22:36:33,098 - freqtrade.commands.trade_commands - ERROR - numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
2022-01-21 22:36:33,099 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/steven/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/steven/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/home/steven/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/steven/freqtrade/freqtrade/freqtradebot.py", line 60, in __init__
    self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
  File "/home/steven/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 44, in load_strategy
    strategy: IStrategy = StrategyResolver._load_strategy(
  File "/home/steven/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 200, in _load_strategy
    strategy = StrategyResolver._load_object(paths=abs_paths,
  File "/home/steven/freqtrade/freqtrade/resolvers/iresolver.py", line 120, in _load_object
    (module, module_path) = cls._search_object(directory=_path,
  File "/home/steven/freqtrade/freqtrade/resolvers/iresolver.py", line 102, in _search_object
    obj = next(cls._get_valid_object(module_path, object_name), None)
  File "/home/steven/freqtrade/freqtrade/resolvers/iresolver.py", line 66, in _get_valid_object
    spec.loader.exec_module(module)  # type: ignore # importlib does not use typehints
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/steven/freqtrade/user_data/strategies/NostalgiaForInfinityX.py", line 7, in <module>
    import talib.abstract as ta
  File "/home/steven/freqtrade/.env/lib/python3.8/site-packages/talib/__init__.py", line 93, in <module>
    from ._ta_lib import (
  File "talib/_ta_lib.pyx", line 1, in init talib._ta_lib
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

```

**Comment by smajka987** [comment]
Turns out it was a Freqtrade installation problem. 

Link to the solution that helped.
[https://github.com/freqtrade/freqtrade/issues/6208#issuecomment-1009957954)](url)
