### ISSUE TITLE
Exception: inputs are all NaN

### ISSUE THREAD

**Issue by a178235** [iterativv/NostalgiaForInfinity#2]
No problems with NFIv7. Looks like it's trying to get BTC/USDT, but I've use */USD.

freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy NostalgiaForInfinityNext
freqtrade.data.history.idatahandler - WARNING - No history data for pair: "BTC/USDT", timeframe: 1h. Use `freqtrade download-data` to download the data
freqtrade.data.dataprovider - WARNING - No data found for (BTC/USDT, 1h).
freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 54, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 552, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 510, in backtest_one_strategy
    preprocessed = self.strategy.ohlcvdata_to_dataframe(data)
  File "/freqtrade/freqtrade/strategy/interface.py", line 733, in ohlcvdata_to_dataframe
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/freqtrade/freqtrade/strategy/interface.py", line 733, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/freqtrade/freqtrade/strategy/interface.py", line 750, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/freqtrade/user_data/strategies/NostalgiaForInfinityNext.py", line 2507, in populate_indicators
    btc_info_tf = self.info_tf_btc_indicators(btc_info_tf, metadata)
  File "/freqtrade/user_data/strategies/NostalgiaForInfinityNext.py", line 2483, in info_tf_btc_indicators
    dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)
  File "talib/_abstract.pxi", line 399, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 441, in talib._ta_lib.Function.__call_function
  File "/home/ftuser/.local/lib/python3.9/site-packages/talib/__init__.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "talib/_func.pxi", line 4365, in talib._ta_lib.RSI
  File "talib/_func.pxi", line 68, in talib._ta_lib.check_begidx1
Exception: inputs are all NaN
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 54, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 552, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 510, in backtest_one_strategy
    preprocessed = self.strategy.ohlcvdata_to_dataframe(data)
  File "/freqtrade/freqtrade/strategy/interface.py", line 733, in ohlcvdata_to_dataframe
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/freqtrade/freqtrade/strategy/interface.py", line 733, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/freqtrade/freqtrade/strategy/interface.py", line 750, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/freqtrade/user_data/strategies/NostalgiaForInfinityNext.py", line 2507, in populate_indicators
    btc_info_tf = self.info_tf_btc_indicators(btc_info_tf, metadata)
  File "/freqtrade/user_data/strategies/NostalgiaForInfinityNext.py", line 2483, in info_tf_btc_indicators
    dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)
  File "talib/_abstract.pxi", line 399, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 441, in talib._ta_lib.Function.__call_function
  File "/home/ftuser/.local/lib/python3.9/site-packages/talib/__init__.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "talib/_func.pxi", line 4365, in talib._ta_lib.RSI
  File "talib/_func.pxi", line 68, in talib._ta_lib.check_begidx1
Exception: inputs are all NaN

**Comment by iterativv** [comment]
It requires 5m & 1h BTC/USDT candle data to exist, in order to complete the backtest.

In dry/live runs, if the pair is available on the exchange, nothing further is needed.

The easy fix is to set a secondary configuration, with USDT stake and only BTC/USDT pair, then download the data for the time range you like to test.
