### ISSUE TITLE
Crash when trying a backtest

### ISSUE THREAD

**Issue by KingDuckZ** [iterativv/NostalgiaForInfinity#235]
I'm trying a backtest with static pairs and I get this crash in the log:

```
2022-08-21 15:39:51 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-08-21 15:39:51 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/usr/lib/python3.10/site-packages/freqtrade/plugins/pairlist/StaticPairList.py'...
2022-08-21 15:39:51 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 480 ...
2022-08-21 15:40:09 - freqtrade.data.history.idatahandler - WARNING - NEXO/BTC, spot, 5m, data starts at 2022-04-29 14:00:00
2022-08-21 15:40:10 - freqtrade.optimize.backtesting - INFO - Loading data from 2022-04-29 08:00:00 up to 2022-08-15 00:00:00 (107 days).
2022-08-21 15:40:10 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy NostalgiaForInfinityX
2022-08-21 15:40:10 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2022-08-21 15:40:10 - freqtrade.data.history.idatahandler - WARNING - No history for BTC/USDT, spot, 1h found. Use `freqtrade download-data` to download the data
2022-08-21 15:40:10 - freqtrade.data.dataprovider - WARNING - No data found for (BTC/USDT, 1h, ).
2022-08-21 15:40:10 - uvicorn.error - ERROR - Exception in ASGI application

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/usr/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/usr/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/usr/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/routing.py", line 68, in app
    await response(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/responses.py", line 170, in __call__
    await self.background()
  File "/usr/lib/python3.10/site-packages/starlette/background.py", line 43, in __call__
    await task()
  File "/usr/lib/python3.10/site-packages/starlette/background.py", line 28, in __call__
    await run_in_threadpool(self.func, *self.args, **self.kwargs)
  File "/usr/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/lib/python3.10/site-packages/freqtrade/rpc/api_server/api_backtest.py", line 98, in run_backtest
    min_date, max_date = ApiServer._bt.backtest_one_strategy(
  File "/usr/lib/python3.10/site-packages/freqtrade/optimize/backtesting.py", line 1155, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "/usr/lib/python3.10/site-packages/freqtrade/strategy/interface.py", line 1129, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/usr/lib/python3.10/site-packages/freqtrade/strategy/interface.py", line 1129, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/usr/lib/python3.10/site-packages/freqtrade/strategy/interface.py", line 1147, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/duckz/.config/freqtrade/strategies/NostalgiaForInfinityX.py", line 10185, in populate_indicators
    btc_info_tf = self.info_tf_btc_indicators(btc_info_tf, metadata)
  File "/home/duckz/.config/freqtrade/strategies/NostalgiaForInfinityX.py", line 10136, in info_tf_btc_indicators
    dataframe['rsi_14'] = ta.RSI(dataframe, timeperiod=14)
  File "talib/_abstract.pxi", line 427, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 472, in talib._ta_lib.Function.__call_function
  File "/usr/lib/python3.10/site-packages/talib/__init__.py", line 64, in wrapper
    result = func(*_args, **_kwds)
  File "talib/_func.pxi", line 4377, in talib._ta_lib.RSI
  File "talib/_func.pxi", line 68, in talib._ta_lib.check_begidx1
Exception: inputs are all NaN
```

**Comment by iterativv** [comment]
Current NFI requires candle data for 5m, 15m, 1h & 1d INCLUDING for BTC. It reports that you don't have BTC/USDT 1h data. So, please include it to your list and download the data again. Also, next version will, most likely, require 4h data too.

**Comment by tahaafg20** [comment]
I have the same issue and even though I have all the BTC/USDT data downloaded for all the timeframes within the timerange it still gives the exact same issue.

**Comment by iterativv** [comment]
This is too old already. If there are still issue, please, don't hesitate to open a new issue.
