### ISSUE TITLE
NostalgiaForInfinityX - New Versions don't start

### ISSUE THREAD

**Issue by Kleingeldprinz** [iterativv/NostalgiaForInfinity#246]
Hi,
thank you for the great Strategies!
I have a problem by using NostalgiaForInfinityX. My last Running Version is from 07.09.22 (2 Days old). When i am using newer Version from the repo, i get this error:

`

2022-09-09 10:02:00,699 - freqtrade.freqtradebot - INFO - Starting freqtrade 2022.8
2022-09-09 10:02:01,645 - NostalgiaForInfinityX - INFO - pandas_ta successfully imported
2022-09-09 10:02:01,647 - freqtrade.commands.trade_commands - ERROR - could not get source code
2022-09-09 10:02:01,647 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 63, in __init__
    self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
  File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 47, in load_strategy
    strategy: IStrategy = StrategyResolver._load_strategy(
  File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 256, in _load_strategy
    strategy = StrategyResolver._load_object(
  File "/freqtrade/freqtrade/resolvers/iresolver.py", line 142, in _load_object
    (module, module_path) = cls._search_object(directory=_path,
  File "/freqtrade/freqtrade/resolvers/iresolver.py", line 124, in _search_object
    obj = next(cls._get_valid_object(module_path, object_name), None)
  File "/freqtrade/freqtrade/resolvers/iresolver.py", line 93, in <genexpr>
    (obj, inspect.getsource(module)) for
  File "/usr/local/lib/python3.10/inspect.py", line 1147, in getsource
    lines, lnum = getsourcelines(object)
  File "/usr/local/lib/python3.10/inspect.py", line 1129, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/local/lib/python3.10/inspect.py", line 958, in findsource
    raise OSError('could not get source code')
OSError: could not get source code

`
Freqtrade won't start anymore.
I am Using Freqtrade in the newest Version.
When i am switching the strategy file "NostalgiaForInfinityX.py" to the old version, everything run fine.

**Comment by iterativv** [comment]
Hi. Maybe you downloaded it manually from github and it's not the raw file in fact ? Try to open it with a text editor.

Either way, download the raw file or clone the repo.

**Comment by Kleingeldprinz** [comment]
Jeez, this is awkward. I deleted the .py and redownloaded via wget in the RAW content. Now it's working (again). Thanks for the help und the awesome work!
