### ISSUE TITLE
NFIX2 does not work for about month, although I follow the daily updates.

### ISSUE THREAD

**Issue by BillyYan13** [iterativv/NostalgiaForInfinity#264]
Operating system: ____ Mac
Python Version: _____ (Python 3.10.7)
CCXT version: _____ (2.4.60)
Freqtrade Version: ____ (`docker-compose run --rm freqtrade -V, 2023.1)

I get this error in logs 2023-02-02 17:48:17,115 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'NostalgiaForInfinityX2'. This class does not exist or contains Python code errors.
freqtrade | 2023-02-02 17:48:17,120 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
freqtrade | Traceback (most recent call last):
freqtrade | File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
freqtrade | worker = Worker(args)
freqtrade | File "/freqtrade/freqtrade/worker.py", line 37, in init
freqtrade | self._init(False)
freqtrade | File "/freqtrade/freqtrade/worker.py", line 53, in _init
freqtrade | self.freqtrade = FreqtradeBot(self._config)
freqtrade | File "/freqtrade/freqtrade/freqtradebot.py", line 63, in init
freqtrade | self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
freqtrade | File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 48, in load_strategy
freqtrade | strategy: IStrategy = StrategyResolver._load_strategy(
freqtrade | File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 274, in _load_strategy
freqtrade | raise OperationalException(

**Comment by JuniorDeveloperUA** [comment]
Hi, i think it can be one of this cases:
1. u use link to file.
2. bad file, just delete it and download new one

**Comment by BillyYan13** [comment]
> Hi, i think it can be one of this cases:
> 
> 1. u use link to file.
> 
> 2. bad file, just delete it and download new one

Thanks for the reply. I deleted it multiple times and tried. It doesn't work. On the other hand, the old NFIX is working with the same settings and everything without any issues.

**Comment by tbrodeen** [comment]
You have an invalid character error, this may be caused by using copy and paste instead of downloading the file.  It may also be related to a non standard character set in your operating system.

**Comment by BillyYan13** [comment]
> You have an invalid character error, this may be caused by using copy and paste instead of downloading the file.  It may also be related to a non standard character set in your operating system.

No and No. I've never copied and pasted the file. Why would I do that? I've always downloaded it. 

If I had a non standards character in my OS, how are the whole Freqtrade amd the old NFIX running smoothly?

**Comment by BillyYan13** [comment]
> You have a very concise message:
> 
> ```
> 
> /freqtrade/user_data/strategies/NostalgiaForInfinityX2.py due to 'invalid character '·' (U+00B7) (NostalgiaForInfinityX2.py, line 72)'
> 
> ```
> 
> Open file /freqtrade/user_data/strategies/NostalgiaForInfinityX2.py
> 
> and just check what is in line 72.
> 
> I don't know about your version, for me the line looks like this:
> 
> ```
> 
>    69     # ROI table:
> 
>    70     minimal_roi = {
> 
>    71         "0": 100.0,
> 
>    72     } <===  It's a closing parenthesis
> 
> ```
> 
> The Unicode character  '·'  (U+00B7) in the strategy Python code is definitely not a valid character :-)

Thanks a lot. I already solved the problem. It has to do with file compatibility with Python, for some reason it kept turning into HTML upon being downloaded instead of Python on the contrary of NFIX1. I finally copied the file and pasted it from Github and it worked. :)
