### ISSUE TITLE
NFIX2 Exception: inputs are all NaN File "talib/_func.pxi", line 4377, in talib._ta_lib.RSI

### ISSUE THREAD

**Issue by sebastianmacias** [iterativv/NostalgiaForInfinity#276]
I'm getting the following error when backtesting NFIX2 v12.0.261:

```
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1343, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1245, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "/freqtrade/freqtrade/strategy/interface.py", line 1301, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/freqtrade/freqtrade/strategy/interface.py", line 1301, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/freqtrade/freqtrade/strategy/interface.py", line 1319, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/freqtrade/user_data/strategies/NostalgiaForInfinityX2.py", line 1807, in populate_indicators
    btc_informative = self.btc_info_switcher(btc_info_pair, btc_info_timeframe, metadata)
  File "/freqtrade/user_data/strategies/NostalgiaForInfinityX2.py", line 1785, in btc_info_switcher
    return self.btc_info_4h_indicators(btc_info_pair, btc_info_timeframe, metadata)
  File "/freqtrade/user_data/strategies/NostalgiaForInfinityX2.py", line 1692, in btc_info_4h_indicators
    btc_info_4h['rsi_14'] = ta.RSI(btc_info_4h, timeperiod=14)
  File "talib/_abstract.pxi", line 445, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 492, in talib._ta_lib.Function.__call_function
  File "/home/ftuser/.local/lib/python3.10/site-packages/talib/__init__.py", line 64, in wrapper
    result = func(*_args, **_kwds)
  File "talib/_func.pxi", line 4377, in talib._ta_lib.RSI
  File "talib/_func.pxi", line 68, in talib._ta_lib.check_begidx1
```

This is the full log:
```
docker-compose run --rm freqtrade backtesting --config user_data/strategies/NostalgiaForInfinityX2/config.json --config user_data/config.private.json --config user_data/strategies/NostalgiaForInfinityX2/config.backtesting.json --strategy NostalgiaForInfinityX2 --timerange 20220601-20220701 --timeframe 5m
2023-03-10 04:32:59,313 - freqtrade - INFO - freqtrade 2023.1
2023-03-10 04:32:59,319 - freqtrade.configuration.load_config - INFO - Using config: user_data/strategies/NostalgiaForInfinityX2/config.json ...
2023-03-10 04:32:59,320 - freqtrade.configuration.load_config - INFO - Using config: user_data/config.private.json ...
2023-03-10 04:32:59,321 - freqtrade.configuration.load_config - INFO - Using config: user_data/strategies/NostalgiaForInfinityX2/config.backtesting.json ...
2023-03-10 04:32:59,322 - freqtrade.loggers - INFO - Verbosity set to 0
2023-03-10 04:32:59,323 - freqtrade.configuration.configuration - INFO - Parameter -i/--timeframe detected ... Using timeframe: 5m ...
2023-03-10 04:32:59,323 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 4 ...
2023-03-10 04:32:59,323 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20220601-20220701 ...
2023-03-10 04:33:00,611 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2023-03-10 04:33:00,611 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2023-03-10 04:33:00,611 - freqtrade.configuration.configuration - INFO - Overriding timeframe with Command line argument
2023-03-10 04:33:00,611 - freqtrade.configuration.configuration - INFO - Parameter --cache=day detected ...
2023-03-10 04:33:00,612 - freqtrade.configuration.configuration - INFO - Filter trades by timerange: 20220601-20220701
2023-03-10 04:33:00,612 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-03-10 04:33:00,620 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2023-03-10 04:33:00,620 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2023-03-10 04:33:00,620 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-03-10 04:33:00,623 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2023-03-10 04:33:00,624 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2023-03-10 04:33:00,624 - freqtrade.exchange.exchange - INFO - Using CCXT 2.7.12
2023-03-10 04:33:00,635 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-03-10 04:33:04,219 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2023-03-10 04:33:04,539 - NostalgiaForInfinityX.1 - INFO - pandas_ta successfully imported
2023-03-10 04:33:04,696 - NostalgiaForInfinityX.2 - INFO - pandas_ta successfully imported
2023-03-10 04:33:04,845 - NostalgiaForInfinityX - INFO - pandas_ta successfully imported
2023-03-10 04:33:04,896 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy NostalgiaForInfinityX2 from '/freqtrade/user_data/strategies/NostalgiaForInfinityX2.py'...
2023-03-10 04:33:04,896 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2023-03-10 04:33:04,897 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2023-03-10 04:33:04,897 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_types' with value in config file: {'entry': 'limit', 'exit': 'limit', 'emergency_exit': 'limit', 'force_entry': 'limit', 'force_exit': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}.
2023-03-10 04:33:04,897 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2023-03-10 04:33:04,897 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2023-03-10 04:33:04,897 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 15, 'exit': 15, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2023-03-10 04:33:04,897 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 4.
2023-03-10 04:33:04,897 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 100.0}
2023-03-10 04:33:04,897 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2023-03-10 04:33:04,897 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.99
2023-03-10 04:33:04,897 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2023-03-10 04:33:04,897 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.01
2023-03-10 04:33:04,897 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.03
2023-03-10 04:33:04,897 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: True
2023-03-10 04:33:04,897 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2023-03-10 04:33:04,897 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2023-03-10 04:33:04,897 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'emergency_exit': 'limit', 'force_entry': 'limit', 'force_exit': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2023-03-10 04:33:04,897 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2023-03-10 04:33:04,897 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2023-03-10 04:33:04,897 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2023-03-10 04:33:04,897 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2023-03-10 04:33:04,898 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 800
2023-03-10 04:33:04,898 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 15, 'exit': 15, 'exit_timeout_count': 0, 'unit': 'minutes'}
2023-03-10 04:33:04,898 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2023-03-10 04:33:04,898 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2023-03-10 04:33:04,898 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: True
2023-03-10 04:33:04,898 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2023-03-10 04:33:04,898 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2023-03-10 04:33:04,898 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2023-03-10 04:33:04,898 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: True
2023-03-10 04:33:04,898 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2023-03-10 04:33:04,898 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 4
2023-03-10 04:33:04,898 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-03-10 04:33:04,905 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
2023-03-10 04:33:05,042 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 800 ...
2023-03-10 04:33:07,005 - freqtrade.data.history.idatahandler - WARNING - APT/USDT, spot, 5m, data starts at 2022-10-19 01:00:00
2023-03-10 04:33:07,006 - freqtrade.data.history.idatahandler - WARNING - No history for APT/USDT, spot, 5m found. Use `freqtrade download-data` to download the data
2023-03-10 04:33:18,889 - freqtrade.optimize.backtesting - INFO - Loading data from 2022-05-29 05:20:00 up to 2022-07-01 00:00:00 (32 days).
2023-03-10 04:33:18,889 - freqtrade.optimize.backtesting - INFO - Dataload complete. Calculating indicators
2023-03-10 04:33:19,065 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy NostalgiaForInfinityX2
2023-03-10 04:33:19,065 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2023-03-10 04:33:19,065 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2023-03-10 04:33:19,275 - freqtrade.data.history.idatahandler - WARNING - BTC/USDT, spot, 4h, data starts at 2023-01-01 00:00:00
2023-03-10 04:33:19,276 - freqtrade.data.history.idatahandler - WARNING - No history for BTC/USDT, spot, 4h found. Use `freqtrade download-data` to download the data
2023-03-10 04:33:19,276 - freqtrade.data.dataprovider - WARNING - No data found for (BTC/USDT, 4h, ).
2023-03-10 04:33:19,276 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1343, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1245, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "/freqtrade/freqtrade/strategy/interface.py", line 1301, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/freqtrade/freqtrade/strategy/interface.py", line 1301, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/freqtrade/freqtrade/strategy/interface.py", line 1319, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/freqtrade/user_data/strategies/NostalgiaForInfinityX2.py", line 1807, in populate_indicators
    btc_informative = self.btc_info_switcher(btc_info_pair, btc_info_timeframe, metadata)
  File "/freqtrade/user_data/strategies/NostalgiaForInfinityX2.py", line 1785, in btc_info_switcher
    return self.btc_info_4h_indicators(btc_info_pair, btc_info_timeframe, metadata)
  File "/freqtrade/user_data/strategies/NostalgiaForInfinityX2.py", line 1692, in btc_info_4h_indicators
    btc_info_4h['rsi_14'] = ta.RSI(btc_info_4h, timeperiod=14)
  File "talib/_abstract.pxi", line 445, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 492, in talib._ta_lib.Function.__call_function
  File "/home/ftuser/.local/lib/python3.10/site-packages/talib/__init__.py", line 64, in wrapper
    result = func(*_args, **_kwds)
  File "talib/_func.pxi", line 4377, in talib._ta_lib.RSI
  File "talib/_func.pxi", line 68, in talib._ta_lib.check_begidx1
Exception: inputs are all NaN
make: *** [backtesting] Error 1
```
Data for BTC/USD exists for the timeframes: 1m 5m 15m 30m 1h 4h 1d

**Comment by sebastianmacias** [comment]
I redownloaded the data and it worked. Closing.
