### ISSUE TITLE
Traceback line 2973 , 2697 informative_1h and request..

### ISSUE THREAD

**Issue by Nai-mul** [iterativv/NostalgiaForInfinity#29]
Hi dev, please remove all data from data/binance... we can download it by using command...otherwise when i am going to clone this git, its just taking too much time.. or please upload only strategy.py file on any cloud...thanks

**Comment by Nai-mul** [comment]
i am using freqtrade develop-b84a1d0c

Traceback (most recent call last):
  File "/home/n/bot_dev/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/n/bot_dev/freqtrade/commands/optimize_commands.py", line 54, in start_backtesting
    backtesting.start()
  File "/home/n/bot_dev/freqtrade/optimize/backtesting.py", line 580, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/home/n/bot_dev/freqtrade/optimize/backtesting.py", line 537, in backtest_one_strategy
    preprocessed = self.strategy.ohlcvdata_to_dataframe(data)
  File "/home/n/bot_dev/freqtrade/strategy/interface.py", line 733, in ohlcvdata_to_dataframe
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/home/n/bot_dev/freqtrade/strategy/interface.py", line 733, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/home/n/bot_dev/freqtrade/strategy/interface.py", line 750, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/n/bot_dev/user_data/strategies/NostalgiaForInfinityNext.py", line 2973, in populate_indicators
    informative_1h = self.informative_1h_indicators(dataframe, metadata)
  File "/home/n/bot_dev/user_data/strategies/NostalgiaForInfinityNext.py", line 2697, in informative_1h_indicators
    informative_1h['ema_12'] = ta.EMA(informative_1h, timeperiod=12)
  File "talib/_abstract.pxi", line 399, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 441, in talib._ta_lib.Function.__call_function
  File "/home/n/bot_dev/.env/lib/python3.9/site-packages/talib/__init__.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "talib/_func.pxi", line 2931, in talib._ta_lib.EMA
  File "talib/_func.pxi", line 68, in talib._ta_lib.check_begidx1
Exception: inputs are all NaN

**Comment by s0undt3ch** [comment]
You're mixing issues.
For the second comment, and issue, make sure you have `pandas-ta` installed.
It's a dependency of this strat.

**Comment by s0undt3ch** [comment]
Hmm, wait, that's a different traceback.
Is talib properly installed?

**Comment by Nai-mul** [comment]
Hi dev, I think so Talib does not understand this informative df.
yes at first i installed pip install ta pandas-ta
then i found this problem. I have tested this strategy in both freqtrade stable and develop version and also i reinstall ta-lib 4.20 and 4.21 but the problem are still present 😝

**Comment by potens1** [comment]
Maybe I'm wrong, but I think this traceback means you don't have the informative data (the BTC 1h) could you check and/or download it (i.e. `-p BTC/USDT -t 1h 5m` or with the FIAT coin you use in `freqtrade download-data`)

**Comment by Nai-mul** [comment]
Ah, I'm the biggest imbalance lunatic man 😭 this problem coming from others (alt_market)Informative pair not from talib.

anyway thanks for you help.
