### ISSUE TITLE
Is it not possible to use futures trade?

### ISSUE THREAD

**Issue by KakaBlce** [iterativv/NostalgiaForInfinity#318]
My config.json：
`{
  "strategy": "NostalgiaForInfinityX4",
  "add_config_files": [
    "configs/trading_mode-futures.json",
    "configs/pairlist-volume-binance-usdt.json",
    "configs/blacklist-binance.json",
    "configs/exampleconfig.json",
    "config-private.json"
  ]
}
`
This error occurred after running
`freqtrade    | 2023-09-05 14:37:23,214 - freqtrade.exchange.exchange - INFO - Using CCXT 4.0.71
freqtrade    | 2023-09-05 14:37:23,214 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap', 'brokerId': None, 'partner': {'spot': {'id': None, 'key': None}, 'future': {'id': None, 'key': None}}}, 'enableRateLimit': True, 'rateLimit': 60}
freqtrade    | 2023-09-05 14:37:23,221 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap', 'brokerId': None, 'partner': {'spot': {'id': None, 'key': None}, 'future': {'id': None, 'key': None}}}, 'enableRateLimit': True, 'rateLimit': 60}
freqtrade    | 2023-09-05 14:37:23,227 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
freqtrade    | 2023-09-05 14:37:25,312 - freqtrade.commands.trade_commands - ERROR - Ticker pricing not available for Binance.
freqtrade    | 2023-09-05 14:37:25,313 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
freqtrade    | Traceback (most recent call last):
freqtrade    |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
freqtrade    |     worker = Worker(args)
freqtrade    |              ^^^^^^^^^^^^
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 37, in __init__
freqtrade    |     self._init(False)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 53, in _init
freqtrade    |     self.freqtrade = FreqtradeBot(self._config)
freqtrade    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade    |   File "/freqtrade/freqtrade/freqtradebot.py", line 76, in __init__
freqtrade    |     self.exchange = ExchangeResolver.load_exchange(
freqtrade    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade    |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 37, in load_exchange
freqtrade    |     exchange = ExchangeResolver._load_exchange(
freqtrade    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade    |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 64, in _load_exchange
freqtrade    |     exchange = ex_class(**kwargs)
freqtrade    |                ^^^^^^^^^^^^^^^^^^
freqtrade    |   File "/freqtrade/freqtrade/exchange/exchange.py", line 187, in __init__
freqtrade    |     self.validate_config(config)
freqtrade    |   File "/freqtrade/freqtrade/exchange/exchange.py", line 231, in validate_config
freqtrade    |     self.validate_pricing(config['exit_pricing'])
freqtrade    |   File "/freqtrade/freqtrade/exchange/exchange.py", line 630, in validate_pricing
freqtrade    |     raise OperationalException(f'Ticker pricing not available for {self.name}.')
freqtrade    | freqtrade.exceptions.OperationalException: Ticker pricing not available for Binance.
`
Can only spot trade be used?

**Comment by iterativv** [comment]
Yes, it's made for spot ... in theory should work in futures, long only. But not fine tuned for that, so no idea how is going to trade.

Later after all planned features done, going to work on futures, probably.

**Comment by godshades** [comment]
@iterativv i'm currently using in future with small amount
bot still doing well but look like stoploss not work in future
hope you can quick add this feature in some day 💯

**Comment by iterativv** [comment]
> @iterativv i'm currently using in future with small amount bot still doing well but look like stoploss not work in future hope you can quick add this feature in some day 💯

Yes, after the planned features complete, we will look into futures. From some dry runs and tests it looks good. But of course, if you want to test for live, with very small amount, that you are fine to loss. Set 10 slots or something like this.

**Comment by iterativv** [comment]
> Can only spot trade be used?

For futures you have to use orderbook too, see configs dir on the repo, example config and the one for futures too.

**Comment by godshades** [comment]
@iterativv hi, i saw we already have > 100 buy condition
may u add some 10 sell condition then back to buy condition bro

**Comment by iterativv** [comment]
> @iterativv hi, i saw we already have > 10 buy condition may u add some 5 sell condition for short then back to buy condition bro

Shorting a bit later, after planned features done.

**Comment by godshades** [comment]
hi @iterativv i saw X4 have custom_stoploss but never happend in future trade, it's alway liquidation
is it normal

**Comment by iterativv** [comment]
> hi @iterativv i saw X4 have custom_stoploss but never happend in future trade, it's alway liquidation
> is it normal

You mean the current NFI ? It should not liquidate. There is de-risk, it's going to sell all stake if big drop, then attempt to recover it. Also, there is grinding before that and after too. This requires latest FT.

**Comment by iterativv** [comment]
This issue should be resolved. Don't hesitate to open a new one, thank you !
