### ISSUE TITLE
TypeError when backtesting NostalgiaForInfinityX

### ISSUE THREAD

**Issue by EdwardZehuaZhang** [iterativv/NostalgiaForInfinity#439]
### **Issue:**
Receiving an TypeError: '<=' not supported between instances of 'float' and 'NoneType' when backtesting NostalgiaForInfinityX.

### **Temporary Fix:**
Replaced line 34303:
`
item_buy_logic.append(dataframe["close_15m"].le(dataframe["close_15m"].shift()))
`

With:
`
item_buy_logic.append(dataframe["close_15m"].fillna(0).le(dataframe["close_15m"].shift().fillna(0)))
`

### **Error:**
```
  df["xe5"].fillna(0, inplace=True)
/freqtrade/user_data/strategies/NostalgiaForInfinityX.py:38687: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["xe6"].fillna(0, inplace=True)
2024-11-11 15:06:42,337 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2024-10-14 02:15:00 up to 2024-11-11 15:00:00 (28 days).
2024-11-11 15:06:42,985 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 44, in main
    return_code = args["func"](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 61, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1649, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1574, in backtest_one_strategy
    results = self.backtest(
              ^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1455, in backtest
    data: dict = self._get_ohlcv_as_lists(processed)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 433, in _get_ohlcv_as_lists
    df_analyzed = self.strategy.ft_advise_signals(pair_data, {"pair": pair})
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/strategy/interface.py", line 1598, in ft_advise_signals
    dataframe = self.advise_entry(dataframe, metadata)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/strategy/interface.py", line 1657, in advise_entry
    df = self.populate_entry_trend(dataframe, metadata)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/user_data/strategies/NostalgiaForInfinityX.py", line 34302, in populate_entry_trend
    item_buy_logic.append(dataframe["close_15m"].le(dataframe["close_15m"].shift()))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/series.py", line 6282, in le
    return self._flex_method(
           ^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/series.py", line 6246, in _flex_method
    return self._binop(other, op, level=level, fill_value=fill_value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/series.py", line 6195, in _binop
    result = func(this_vals, other_vals)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'float' and 'NoneType'
```

**Comment by iterativv** [comment]
Hi, is this X ? Well, it's because the pair is new, I assume, so not all data is available, especially for higher time frames.

Also note, better to use X5 now.

**Comment by EdwardZehuaZhang** [comment]
Appreciate the quick reply iterativv. Great repository, just got started. I understand where this is comming from, will play around a bit and switch to X5!
