### ISSUE TITLE
 An error occurs in freqtrade 2021.07 version. --> freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED

### ISSUE THREAD

**Issue by Jungdol** [iterativv/NostalgiaForInfinity#63]
I used google translator. sorry

I am using the freqtrade version 2021.7
The 2021.06 version seems to work fine .. maybe..?

I typed this in ssh.

screen\n
cd ~/freqtrade/
python3 -m venv .env
source .env/bin/activate
python3 -m pip install --upgrade pip
python3 -m pip install -e .
pip install pandas_ta
freqtrade trade -c ./user_data/config-binance.json --strategy NostalgiaForInfinityNext

However, an error occurred and it did not run.

2021-08-10 01:47:29,757 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `ask_strategy.use_sell_signal` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `use_sell_signal` setting in your configuration instead.
2021-08-10 01:47:29,757 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `ask_strategy.sell_profit_only` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `sell_profit_only` setting in your configuration instead.
2021-08-10 01:47:29,757 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `ask_strategy.ignore_roi_if_buy_signal` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `ignore_roi_if_buy_signal` setting in your configuration instead.
2021-08-10 01:47:29,757 - freqtrade.freqtradebot - INFO - Starting freqtrade 2021.7
2021-08-10 01:47:29,805 - freqtrade.resolvers.iresolver - WARNING - Could not import /root/freqtrade/user_data/strategies/NostalgiaForInfinityNext.py due to 'libta_lib.so.0: cannot open shared object file: No such file or directory'
2021-08-10 01:47:29,805 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'NostalgiaForInfinityNext'. This class does not exist or contains Python code errors.
2021-08-10 01:47:29,805 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/root/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/root/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 60, in __init__
    self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
  File "/root/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 44, in load_strategy
    strategy: IStrategy = StrategyResolver._load_strategy(
  File "/root/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 212, in _load_strategy
    raise OperationalException(
freqtrade.exceptions.OperationalException: Impossible to load Strategy 'NostalgiaForInfinityNext'. This class does not exist or contains Python code errors.

![image](https://user-images.githubusercontent.com/61561973/128796916-380f2542-a1e7-4dff-a388-0d101831934d.png)

**Comment by abc112116** [comment]
You should remove those deprecated `ask_strategy.use_sell_signal` `ask_strategy.sell_profit_only` `ask_strategy.ignore_roi_if_buy_signal` settings  from your config files as warning says, and make sure `NostalgiaForInfinityNext.py` is in `user_data/strategies` folder.

**Comment by Jungdol** [comment]
> `ask_strategy.use_sell_signal` `ask_strategy.sell_profit_only` `ask_strategy.ignore_roi_if_buy_signal`경고에 따라 구성 파일에서 더 이상 사용되지 않는 설정을 제거 `NostalgiaForInfinityNext.py`하고 `user_data/strategies`폴더에 있는지 확인해야 합니다.

Thank you very much! I had to modify the config.
