### ISSUE TITLE
 Unable to analyze candle (OHLCV) data for pair DGB/USDT: input_arrays parameter missing required data key: ema1

### ISSUE THREAD

**Issue by LucianPopaLVP** [iterativv/NostalgiaForInfinity#88]
Hi there, ive been running this strat live since sunday...everything worked fine until few hours ago when my console started spamming  and I am getting this error and can not find in the strategy a ema1 that can cause it , what would be the problem?

2021-08-19 11:16:40,594 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair DGB/USDT: input_arrays parameter missing required data key: ema1
2021-08-19 11:16:40,598 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error input_arrays parameter missing required data key: ema1 calling <bound method IStrategy._analyze_ticker_internal of <strategy.strategy object at 0x7fdc0e631a30>>
Traceback (most recent call last):
File "/home/lvp/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
return f(*args, **kwargs)
File "/home/lvp/freqtrade/freqtrade/strategy/interface.py", line 417, in _analyze_ticker_internal
dataframe = self.analyze_ticker(dataframe, metadata)
File "/home/lvp/freqtrade/freqtrade/strategy/interface.py", line 396, in analyze_ticker
dataframe = self.advise_indicators(dataframe, metadata)
File "/home/lvp/freqtrade/freqtrade/strategy/interface.py", line 750, in advise_indicators
return self.populate_indicators(dataframe, metadata)
File "/home/lvp/freqtrade/user_data/strategies/strategy.py", line 2915, in populate_indicators
informative_1h = self.informative_1h_indicators(dataframe, metadata)
File "/home/lvp/freqtrade/user_data/strategies/strategy.py", line 2593, in informative_1h_indicators
informative_1h['ema_12'] = ta.EMA(informative_1h, timeperiod=12)
File "talib/_abstract.pxi", line 398, in talib._ta_lib.Function.call
File "talib/_abstract.pxi", line 270, in talib._ta_lib.Function.set_function_args
File "talib/_abstract.pxi", line 221, in talib._ta_lib.Function.set_input_arrays
Exception: input_arrays parameter missing required data key: ema1
2021-08-19 11:16:40,598 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair ICX/USDT: input_arrays parameter missing required data key: ema1
2021-08-19 11:16:40,602 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error input_arrays parameter missing required data key: ema1 calling <bound method IStrategy._analyze_ticker_internal of <strategy.strategy object at 0x7fdc0e631a30>>
Traceback (most recent call last):

haven't made any chances until today when started spamming.
Reinstalled all from fresh and it keeps spamming, 
Unable to analyze candle OHLCV data for pairs: imputs are all NAN
ERROR  - Unexpected error inputs are all NAN calling <bound method Istrategy._analyze_ticker_internal of<infinitynext.infinitynext object at 0x7fef705febb0>>

Do not know /understand what is happening....its showing this for all the pairs in the dynamic list i have set in the config. :(
Please help!

**Comment by abc112116** [comment]
Look like DDOS protection from exchange. Increase your rate limit would help in long terms

**Comment by LucianPopaLVP** [comment]
> Look like DDOS protection from exchange. Increase your rate limit would help in long terms

Translate please? :))  what limit should i increase?

**Comment by jurekl** [comment]
"exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 20010  <=========== HERE !!!
        },

**Comment by LucianPopaLVP** [comment]
> ```
> "exchange": {
>     "name": "binance",
>     "key": "",
>     "secret": "",
>     "ccxt_config": {"enableRateLimit": true},
>     "ccxt_async_config": {
>         "enableRateLimit": true,
>         "rateLimit": 200  <=========== HERE !!!
>     },
> ```

no go. i am still getting the error. :(

**Comment by HenriPiot-dev** [comment]
I got the same error from today, my bot is running for 6 days ! 
This Is a log exemple : 
freqtrade.strategy.interface: WARNING - Empty candle (OHLCV) data for pair OMG/USDT
My rate limit is set to 300

**Comment by LucianPopaLVP** [comment]
> I got the same error from today, my bot is running for 6 days !
> This Is a log exemple :
> freqtrade.strategy.interface: WARNING - Empty candle (OHLCV) data for pair OMG/USDT
> My rate limit is set to 300

don't know what is the problem....the error came back today, after I've done nothing in the first place to fix it :( just restarted everything and worked in that day, but doesn't;t work today .

**Comment by eSeR1805** [comment]
Are you using docker or native install?
what does this output?
`<curl -s -D - "https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=1h">`

**Comment by topscoder** [comment]
Had same issue here. Fixed by installing `pandas-ta`:

```shell
pip install pandas-ta
```

**Comment by eSeR1805** [comment]
> should I just go ahead and install this?

Yes

**Comment by LucianPopaLVP** [comment]
> > should I just go ahead and install this?
> 
> Yes. Also tell us if you're using docker or not.

not using docker, just native install.

**Comment by Galerion1974** [comment]
I had similar issue. Might have found the reason. 

Initial error, and this was for most if not all coins: 
`freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair CELR/EUR: input_arrays parameter missing required data key: ema1`

By suggestion from @topscoder I did "pip install pandas-ta".

Now log just mentioned one coin:
`freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair CELR/EUR: inputs are all NaN`

I found out that on my exchange (Bitvavo) CELR was blocked from trading.  So api-request must have reported NaN witch must have threw off the script. I blacklisted this coin and now it appears to be working.

**Comment by LucianPopaLVP** [comment]
> Had same issue here. Fixed by installing `pandas-ta`:
> 
> ```shell
> pip install pandas-ta
> ```

didn't help! already had that library installed :(

**Comment by Gjuju** [comment]
Try with Pandas_ta instead of pandas-ta

**Comment by eSeR1805** [comment]
@LucianPopaLVP is this still a problem?
