### ISSUE TITLE
Hold trades file support broken ?

### ISSUE THREAD

**Issue by potens1** [iterativv/NostalgiaForInfinity#95]
Hi, I don't know if the hold trades is still working (in my case, it sold something that was in the old path, but old path or new one, this error always come)                                                    
                                                                                  
```2021-08-20 16:41:01,307 - NostalgiaForInfinityNext - WARNING - Loading hold support data from /srv/ft_userdata/user_data/nfi-hold-trades.json
NostalgiaForInfinityNext - WARNING - Loading hold support data from /srv/ft_userdata/user_data/nfi-hold-trades.json
2021-08-20 16:41:01,308 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error dictionary changed size during iteration calling <bound method NostalgiaForInfinityNext.bot_loop_start of <NostalgiaForInfinityNext.NostalgiaForInfinityNext object a>
Traceback (most recent call last):
  File "/opt/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/srv/NostalgiaForInfinity/NostalgiaForInfinityNext.py", line 2128, in bot_loop_start
    self.load_hold_trades_config()
  File "/srv/NostalgiaForInfinity/NostalgiaForInfinityNext.py", line 2104, in load_hold_trades_config
    self.hold_trades_cache = HoldsCache(hold_trades_config_file)
  File "/srv/NostalgiaForInfinity/NostalgiaForInfinityNext.py", line 4250, in __init__
    self.load()
  File "/srv/NostalgiaForInfinity/NostalgiaForInfinityNext.py", line 4264, in load
    self._load()
  File "/srv/NostalgiaForInfinity/NostalgiaForInfinityNext.py", line 4284, in _load
    self.data = self.process_loaded_data(data)
  File "/srv/NostalgiaForInfinity/NostalgiaForInfinityNext.py", line 4329, in process_loaded_data
    for trade in open_trades.values():
RuntimeError: dictionary changed size during iteration
freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error dictionary changed size during iteration calling <bound method NostalgiaForInfinityNext.bot_loop_start of <NostalgiaForInfinityNext.NostalgiaForInfinityNext object at 0x7f51475a6100>>
Traceback (most recent call last):
  File "/opt/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/srv/NostalgiaForInfinity/NostalgiaForInfinityNext.py", line 2128, in bot_loop_start
    self.load_hold_trades_config()
  File "/srv/NostalgiaForInfinity/NostalgiaForInfinityNext.py", line 2104, in load_hold_trades_config
    self.hold_trades_cache = HoldsCache(hold_trades_config_file)
  File "/srv/NostalgiaForInfinity/NostalgiaForInfinityNext.py", line 4250, in __init__
    self.load()
  File "/srv/NostalgiaForInfinity/NostalgiaForInfinityNext.py", line 4264, in load
    self._load()
  File "/srv/NostalgiaForInfinity/NostalgiaForInfinityNext.py", line 4284, in _load
    self.data = self.process_loaded_data(data)
  File "/srv/NostalgiaForInfinity/NostalgiaForInfinityNext.py", line 4329, in process_loaded_data
    for trade in open_trades.values():
RuntimeError: dictionary changed size during iteration

```

**Comment by potens1** [comment]
Resolved by 6014e48
